### ISSUE TITLE
External Config

### ISSUE THREAD

**Issue by LLParse** [chrisurwin/localranchervagrant#15]
As new features are added, existing installations get out of sync and require full recreation or manual intervention to fix. Users shouldn't need to modify Bash or Ruby files.

Externalize the configuration parameters to an answers file, check-in reasonable default config, and add default config to `.gitignore`.

**Comment by chrisurwin** [comment]
Prefer it if vagrant file contained default settings that could be overriden by external config

**Comment by chrisurwin** [comment]
Done
